<?php

/** @var \Algolia\AlgoliaSearch\Block\Algolia $block */
$priceKey = $block->getPriceKey();

$origFormatedVar = 'price' . $priceKey . '_original_formated';

?>

<!-- Product hit template -->
<script type="text/template" id="autocomplete_products_template">
    <a class="algoliasearch-autocomplete-hit" href="{{url}}">
        {{#thumbnail_url}}
        <div class="thumb"><img src="{{thumbnail_url}}" /></div>
        {{/thumbnail_url}}

        <div class="info">
            {{{_highlightResult.name.value}}}

            <div class="algoliasearch-autocomplete-category">
                {{#categories_without_path}}
                <?php echo __('in'); ?> {{{categories_without_path}}}
                {{/categories_without_path}}

                {{#_highlightResult.color}}
                {{#_highlightResult.color.value}}
                <span>
                    {{#categories_without_path}} | {{/categories_without_path}}
                    Color: {{{_highlightResult.color.value}}}
                </span>
                {{/_highlightResult.color.value}}
                {{/_highlightResult.color}}
            </div>

            <div class="algoliasearch-autocomplete-price">
                    <span class="after_special
                                {{#<?php echo $origFormatedVar; ?>}}promotion{{/<?php echo $origFormatedVar; ?>}}">
                        {{price<?php echo $priceKey; ?>_formated}}
                    </span>

                {{#<?php echo $origFormatedVar; ?>}}
                    <span class="before_special">
                        {{<?php echo $origFormatedVar; ?>}}
                    </span>
                {{/<?php echo $origFormatedVar; ?>}}
            </div>
        </div>
    </a>
</script>