<?php
/** @var \Algolia\AlgoliaSearch\ViewModel\Recommend\Cart $block */
$viewModel = $block->getViewModel();
$recommendConfig = $viewModel->getAlgoliaRecommendConfiguration();
if (!empty($recommendConfig['enabledRelatedInCart'])
    || !empty($recommendConfig['enabledFBTInCart'])
    || !empty($recommendConfig['isTrendItemsEnabledInCartPage'])
    || !empty($recommendConfig['isLookingSimilarEnabledInCartPage'])):
    $cartItems = $viewModel->getAllCartItems();
    ?>
    <div id="algoliaRecommend">
        <div id="frequentlyBoughtTogether" class="recommend-component"></div>
        <div id="relatedProducts" class="recommend-component"></div>
        <div id="trendItems" class="trendsItem recommend-component"></div>
        <div id="lookingSimilar" class="lookingSimilar recommend-component"></div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Algolia_AlgoliaSearch/js/recommend" : {
                    "objectIDs" : <?= /* @noEscape */ json_encode($cartItems, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP) ?>
                }
            }
        }
    </script>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form]": {
                "catalogAddToCart": {}
            }
        }
    </script>
<?php endif; ?>
