
<?php if (!empty($block->getAnalytics())): ?>
    <div id="algolia-analyatics-diagram"></div>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load("current", {packages:['corechart']});
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {

            var data = new google.visualization.arrayToDataTable([
                ['Date', 'Searches', {type: 'string', role: 'tooltip', p: {'html': true}}, {role: 'style'}],
            ]);

            var options = {
                chart: {
                    subtitle: 'Searches, Users, and No Result Rates',
                },
                colors: ['#5468ff', '#3a46a1', '#3ab2bd'],
                hAxis: {
                    baselineColor: 'grey',
                    textStyle: {
                        color: 'grey'
                    }
                },
                vAxis: {
                    baselineColor: 'grey',
                    minValue: 0,
                    textStyle: {
                        color: 'grey'
                    }
                },
                legend: {position: 'none'},
                tooltip: {isHtml: true},
                fontSize: 12,
                fontName: 'Open Sans'
            };

            var chart = new google.visualization.ColumnChart(document.getElementById('algolia-analyatics-diagram'));
            chart.draw(data, options);
        }
    </script>
<?php endif ?>
