<?php /** @var $this \Algolia\AlgoliaSearch\Block\Adminhtml\Support\Components\LegacyVersion */ ?>

<script>
	var algoliaSearchExtentionsVersion = "<?php echo $this->getExtensionVersion(); ?>"
</script>

<div class="legacy_version">
    You’re running version <span id="current_version" class="version"></span>.
    The latest available version is <span id="latest_version" class="version"></span>.
    Please, update the extension and see if the issues persists.

    <a href="https://community.algolia.com/magento/doc/m2/upgrade/" target="_blank">How to update?</a>
</div>
