<?php
/** @var \Magento\Backend\Block\Template $block */
?>
<div class="algolia-indexing-manager-overview">
    <div class="algolia_dashboard_warning">
        <p>Here is a list of all the indices created by the extension on the Algolia Dashboard.</p>
        <p>Those indices are listed by store for each entity section. You can click on them to directly open the Algolia Dashboard.</p>
    </div>


    <?php echo $block->getChildHtml('indexing_manager_products') ?>
    <?php echo $block->getChildHtml('indexing_manager_categories') ?>
    <?php echo $block->getChildHtml('indexing_manager_pages') ?>
 </div>
