version: 2.1

executors:
  magento-executor:
    parameters:
      php-version:
        type: string
      magento-version:
        type: string
    docker:
      - image: markoshust/magento-php:<<parameters.php-version>>-fpm
    environment:
      MAGENTO_VERSION: <<parameters.magento-version>>
      PHP_VERSION: <<parameters.php-version>>

jobs:
  magento-build:
    parameters:
      php-version:
        type: string
      magento-version:
        type: string
    executor:
      name: magento-executor
      php-version: <<parameters.php-version>>
      magento-version: <<parameters.magento-version>>
    steps:
      - attach_workspace:
          at: ~
      - checkout
      - run:
          name: Setup magento enterprise
          command: |
            curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento-enterprise.test <<parameters.magento-version>>
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "composer.lock" }}
            - v1-deps-
      - run:
          name: Install dependencies via composer
          command: |
            composer require algolia/algoliasearch-client-php "^4.0"
      - save_cache:
          key: v1-deps-{{ checksum "composer.lock" }}
          paths:
            - ~/.composer/cache
            - vendor
      - run:
          name: Setup Magento
          command: |
            echo "Setting up Magento $MAGENTO_VERSION"
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  magento-build-and-test:
    jobs:
      - magento-build:
          matrix:
            parameters:
              php-version: ["8.2"]
              magento-version: ["2.4.6", "2.4.7"]
          filters:
            branches:
              only:
                - MAGE-991