version: 2.1

parameters:
  php-version:
    type: string
    default: "8.2"
  magento-version:
    type: string
    default: "2.4.6"

executors:
  magento-executor:
    machine:
      image: ubuntu-2404:2024.11.1

jobs:
  magento-build:
    executor:
      name: magento-executor
    steps:
      - checkout
      - run:
          name: Setup magento enterprise
          command: |
            curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
            bin/download enterprise <<parameters.magento-version>>
            bin/setup magento-enterprise.test


workflows:
  magento-build-and-test:
    jobs:
      - magento-build:
          matrix:
            parameters:
              php-version: ["8.2"]
              magento-version: ["2.4.6", "2.4.7"]
          filters:
            branches:
              only:
                - MAGE-991