version: 2.1

orbs:
  php: circleci/php@2.0.0

executors:
  magento-executor:
    machine:
      image: ubuntu-2404:2024.11.1

jobs:
  magento-build:
    executor:
      name: magento-executor
    parameters:
      php-version:
        type: string
      magento-version:
        type: string
    steps:
      - checkout
      - php/install_php:
          version: << parameters.php-version >>
      - php/install_composer
      - run:
          name: Configure composer authentication
          command: |
            composer config --global http-basic.repo.magento.com ${MAGENTO_AUTH_USERNAME} ${MAGENTO_AUTH_PASSWORD}
      - run:
          name: Setup magento enterprise
          command: |
            mkdir ~/Sites
            cd ~/Sites
            curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
            bin/start --no-dev
            bin/setup-composer-auth
            bin/cli git clone git@github.com:magento/magento2.git .
            bin/cli git checkout << parameters.magento-version >>>-develop
            bin/composer install
            bin/composer require algolia/algoliasearch-client-php "^4.0"

workflows:
  magento-build-and-test:
    jobs:
      - magento-build:
          matrix:
            parameters:
              php-version: ["8.2"]
              magento-version: ["2.4.6", "2.4.7"]
          filters:
            branches:
              only:
                - MAGE-991