version: 2.1

orbs:
  php: circleci/php@2.0.0

executors:
  magento-executor:
    machine:
      image: ubuntu-2404:2024.11.1
      docker_layer_caching: true

jobs:
  magento-build:
    executor:
      name: magento-executor
    parameters:
      php-version:
        type: string
      magento-version:
        type: string
    steps:
      - checkout
      - php/install_php:
          version: << parameters.php-version >>
      - php/install_composer
      - run:
          name: Configure composer authentication
          command: |
            composer config --global http-basic.repo.magento.com ${MAGENTO_AUTH_USERNAME} ${MAGENTO_AUTH_PASSWORD}
      - run:
          name: Setup folder structure and override file
          command: |
            mkdir ~/Sites
            cd ~/Sites
            cat \<<EOF > compose.override.yml
            services:
              phpfpm:
                image: markoshust/magento-php:<< parameters.php-version >>-fpm
            EOF
      - run:
          name: Setup magento enterprise
          working_directory: ~/Sites
          command: |
            curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
            docker compose -f compose.yaml -f compose.override.yml up -d --remove-orphans 
            bin/fixowns
            bin/setup-composer-auth
            bin/cli git clone git@github.com:magento/magento2.git .
            bin/cli git checkout tags/<< parameters.magento-version >>-p6
            bin/composer install
      - run:
          name: Configure AlgoliaSearch extension
          working_directory: ~/Sites
          command: |
            cp -r ~/project/ AlgoliaSearch
            bin/cli mkdir -p app/code/Algolia
            docker cp AlgoliaSearch/ "$(bin/docker-compose ps -q phpfpm|awk '{print $1}')":/var/www/html/app/code/Algolia
            bin/fixowns
            bin/fixperms
      - run:
          name: Enable AlgoliaSearch extension
          working_directory: ~/Sites
          command: |
            bin/magento module:enable Algolia_AlgoliaSearch
      - run:
          name: Compile AlgoliaSearch extension
          working_directory: ~/Sites
          command: |
            bin/composer require algolia/algoliasearch-client-php "^4.0" -W
            bin/magento setup:di:compile
            bin/magento module:status Algolia_AlgoliaSearch

workflows:
  magento-build-and-test:
    jobs:
      - magento-build:
          matrix:
            parameters:
              php-version: ["8.2"]
              magento-version: ["2.4.6", "2.4.7"]
