<style type="text/css">
    .algolia-notice { margin-bottom: 2rem; }
</style>

<?php if ($this->isQueueActive()) : ?>
    <div class="message message-notice notice algolia-notice">
        <div data-ui-id="messages-message-notice">
            <?php /* @escapeNotVerified */ echo __('Status of the queue : <strong>%1</strong>.', $this->getQueueRunnerStatus()); ?>
            <p><?php /* @escapeNotVerified */ echo __('Last Update : <strong>%1</strong>.', $this->getLastQueueUpdate()); ?></p>
            <?php if ($this->isQueueStuck()) : ?>
                <p>
                    <a href="<?php echo $this->getResetQueueUrl() ?>"><?php /* @escapeNotVerified */ echo __('Reset queue'); ?></a>
                </p>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>