<?php

/** @var $this \Magento\Backend\Block\Template */

/** @var \Algolia\AlgoliaSearch\ViewModel\Adminhtml\Common $viewModel */
$viewModel = $this->getViewModel();

$isClickAnalyticsEnabled = true;
$isClickAnalyticsTurnedOnInAdmin = true;
$isQueryRulesEnabled = true;

$section = $this->getRequest()->getParam('section');

if ($section === 'algoliasearch_cc_analytics') {
    $isClickAnalyticsEnabled = $viewModel->isClickAnalyticsEnabled();
    $isClickAnalyticsTurnedOnInAdmin = $viewModel->isClickAnalyticsTurnedOnInAdmin();
}

if ($section === 'algoliasearch_instant') {
    $isQueryRulesEnabled = $viewModel->isQueryRulesEnabled();
}

$ajaxCheckUrl = $this->getUrl('algolia_algoliasearch/landingpage/checkUrl');
$ajaxCheckQuery = $this->getUrl('algolia_algoliasearch/query/checkQuery');

$linksAndVideoTemplate = $viewModel->getLinksAndVideoTemplate($section);
$isEsWarningNeeded = $viewModel->isEsWarningNeeded();
$extensionNotices = $viewModel->getExtensionNotices();

?>

<script>
var isClickAnalyticsEnabled = <?php echo json_encode($isClickAnalyticsEnabled); ?>;
var isClickAnalyticsTurnedOnInAdmin = <?php echo json_encode($isClickAnalyticsTurnedOnInAdmin); ?>;
var isQueryRulesEnabled = <?php echo json_encode($isQueryRulesEnabled); ?>;

var ajaxCheckUrl = <?php echo json_encode($ajaxCheckUrl); ?>;
var ajaxCheckQuery = <?php echo json_encode($ajaxCheckQuery); ?>;
var linksAndVideoTemplate = <?php echo json_encode($linksAndVideoTemplate); ?>;

var isEsWarningNeeded = <?php echo json_encode($isEsWarningNeeded); ?>;
var extensionNotices = <?php echo json_encode($extensionNotices); ?>;

document.addEventListener("DOMContentLoaded", function(event) {
	requirejs(['algoliaAdminBundle'], function(algoliaAdminBundle) {
		algoliaAdminBundle.$(function ($) {
			$('form[action*="algoliasearch"] .accordion .config .label').css('width', 'auto');
			$('form[action*="algoliasearch"] .accordion .config .value').css('width', 'auto');

			var fixHelper = function(e, ui) {
				ui.children().each(function() {
					$(this).width($(this).width());
				});

				return ui;
			};

			setTimeout(function () {
				$('form[action*="algoliasearch"] .admin__control-table tbody').sortable({
					containment: "parent",
					items: 'tr',
					tolerance: 'pointer',
					helper: fixHelper,
					start: function (event, ui) {
						$(ui.item).css('margin-left', '10px');
					}
				});

				$('form[action*="algoliasearch"] .admin__control-table tbody tr td').css('cursor', 'move');
			}, 1000);

			/** FEATURE ENABLEMENT **/
			var notEnabledText = `
				<br>
				<div class="algolia_block icon-stars">
					To get access to this Algolia feature,
					please consider <a href="https://www.algolia.com/billing/overview" target="_blank">upgrading to a higher plan</a>.
				</div>
			`;

			/** FEATURE ACTIVATION **/
			var notActivatedText = `
			<tr>
				<td colspan="3">
					<div class="algolia_block blue icon-stars">
					Enhance your Analytics with <b>Algolia Click Analytics</b> that provide you even more insights
					like Click-through Rate, Conversion Rate from searches and average click position.
					Click Analytics are only available for higher plans and require only minor additional settings.
					<br><br>
					Find more information in <a href="https://www.algolia.com/doc/integration/magento-2/how-it-works/click-and-conversion-analytics/?utm_source=magento&utm_medium=extension&utm_campaign=magento_2&utm_term=shop-owner&utm_content=doc-link" target="_blank">documentation</a>.
					</div>
				</td>
			</tr>
			`;

			// Click analytics
			if (isClickAnalyticsEnabled === false) {
				$('#algoliasearch_cc_analytics_cc_analytics_group table').hide();
				$('#algoliasearch_cc_analytics_cc_analytics_group .comment').after(notEnabledText);
			}

			if (isClickAnalyticsEnabled === true && isClickAnalyticsTurnedOnInAdmin === false) {
				$('#row_algoliasearch_cc_analytics_cc_analytics_group_enable').before(notActivatedText);
			}

			// Query rules in facets
			if (isQueryRulesEnabled === false) {
				var notEnabledText = `
					<br>
					<div class="algolia_block icon-stars">
						To be able to create Query rules for facets,
						please consider <a href="https://www.algolia.com/billing/overview" target="_blank">upgrading to a higher plan</a>.
					</div>
				`;

				$('select[name*=create_rule]').val('2').prop('disabled', 'disabled');
				$('#row_algoliasearch_instant_instant_facets .algolia_block.blue').after(notEnabledText);
			}

			var url = window.location.href;
			if (url.indexOf('section/algoliasearch_') !== -1) {

				// Adding links and videos to the config panel
                $('.algolia-admin-content').html(linksAndVideoTemplate);

            	// New notice management
            	extensionNotices.each(function(notice){
            		if (notice.method === 'before') {
        				$(notice.selector).before(notice.message);
        			} else if (notice.method === 'append') {
						$(notice.selector).append(notice.message);
        			}
            	});

			}

			// SYNONYMS

			handleSynonyms($('#algoliasearch_synonyms_synonyms_group_enable_synonyms').val());

			$(document).on('change', '#algoliasearch_synonyms_synonyms_group_enable_synonyms', function() {
				handleSynonyms($(this).val());
			});

			function handleSynonyms(enabled) {
				var $rows = $('#row_algoliasearch_synonyms_synonyms_group_synonyms, #row_algoliasearch_synonyms_synonyms_group_oneway_synonyms, #row_algoliasearch_synonyms_synonyms_group_synonyms_file');

				if (enabled === '1') {
					$rows.show();
				} else {
					$rows.hide();
				}
			}

			// ORDERED / UNORDERED
			var $attributesRows = $('#algoliasearch_products_products_product_additional_attributes, #algoliasearch_categories_categories_category_additional_attributes');
			initAttributes($attributesRows);

			$attributesRows.on('click', 'button[id^="addToEndBtn"]', function (e) {
				initAttributes($attributesRows);
			});

			$attributesRows.on('change', 'select[name$="[searchable]"]', function (e) {
				handleAttributes($(this));
			});

			function initAttributes($attributesRows) {
				$attributesRows.find('select[name$="[searchable]"]').each(function(e) {
					handleAttributes($(this));
				});
			}

			function handleAttributes($selectBox) {
				var selectValue = $selectBox.val(),
					$input = $selectBox.parent('td').next().find('select[name$="[order]"]');

				if(selectValue !== '1') {
					$input.hide();
				}
				else {
					$input.show();
				}
			}

			// EVENT TRACKING
            algoliaEventsTracking.track();

		});
	});

	requirejs([
		'jquery',
		'Magento_Ui/js/lib/validation/validator',
		'mage/translate',
        'prototype'
	], function ($, validator, mage) {
		'use strict';

      $(".close-box").click(function() {
        $(this).parent().hide();
      });

      validator.addRule(
        'validate-query-usage',
        function (value) {
          var isValid = true;
          var storeId = $('select[name="store_id"]').val();
          var queryId = $('input[name="query_id"]').val();

          var url = ajaxCheckQuery;

          // Only check if the focus is not on the search
          if ($(':focus').attr('name') != 'query_text') {
              new Ajax.Request(
                url,
                {
                    parameters: {'store_id': storeId, 'query_text': value, 'query_id': queryId},
                    method: 'post',
                    asynchronous: false,
                    onComplete: function (transport) {
                    var response = JSON.parse(transport.responseText);
                    isValid = response.isValid;
                }
              }
            );
          }

          return isValid;
        },
        $.mage.__('This query is already connected to another query rule. Please enter a different query or edit the existing one.')
      );

      validator.addRule(
        'validate-algolia-index',
        function (value) {

          if (typeof window.algoliaSearchConfig.indexDataByStoreIds[value]== "undefined") {
            return false;
          }

          return true;
        },
        $.mage.__('The index corresponding to the store you selected doesn\'t exist.')
      );

        validator.addRule(
            'validate-url-unicity',
            function (value) {
                var isValid = false;
                var storeId = $('select[name="store_id"]').val();
                var landingPageId = $('input[name="landing_page_id"]').val();
                var url = ajaxCheckUrl;

                new Ajax.Request(
                    url,
                    {
                        parameters: {'store_id': storeId, 'url_key': value, 'landing_page_id': landingPageId},
                        method: 'post',
                        asynchronous: false,
                        onComplete: function (transport) {
                            var response = JSON.parse(transport.responseText);
                            isValid = response.isValid;
                        }
                    }
                );
                return isValid;
            },
            $.mage.__('This URL key is already in use. Please find another one.')
        );
        if (isEsWarningNeeded) {
        	$('#algoliasearch_instant_instant_backend_rendering_enable').attr('disabled','disabled');
	        $('#algoliasearch_instant_instant_is_instant_enabled').on('change', function(){
				$('#algoliasearch_instant_instant_backend_rendering_enable').attr('disabled','disabled');
			});
		}
	});
});
</script>
