<?php /** @var \Magento\Framework\Escaper $escaper */?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a href="<?= $escaper->escapeUrl($filterItem->getUrl()) ?>">
                    <?= $escaper->escapeHtml($filterItem->getLabel()) ?>
                    <?php if ($block->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?= $escaper->escapeHtml($filterItem->getCount()) ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?= $escaper->escapeHtml(__('item')) ?>
                            <?php else:?> <?= $escaper->escapeHtml(__('items')) ?><?php endif; ?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?= $escaper->escapeHtml($filterItem->getLabel()) ?>
                <?php if ($block->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?= $escaper->escapeHtml($filterItem->getCount()) ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?= $escaper->escapeHtml(__('item')) ?>
                        <?php else:?><?= $escaper->escapeHtml(__('items')) ?><?php endif; ?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
