<?php
/** @var \Magento\Backend\Block\Template $block */
?>
<div class="algolia-admin-content">
    <div class="algolia-admin-content-wrapper">
        <div class="algolia-admin-content-links">
            <p>
                <span>
                    <img src="<?php echo $block->escapeUrl($block->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-docs.svg')) ?>">
                    <a target="_blank" href="https://www.algolia.com/doc/integration/magento-2/how-it-works/indexing-queue/#indexing-queue-archives"><?php echo $block->escapeHtml(__('Indexing queue archives documentation')) ?></a>
                </span>
            </p>
        </div>
    </div>
</div>
