<?php

/** @var \Algolia\AlgoliaSearch\Block\Adminhtml\Category\Merchandising $block */

?>

<?php if ($block->isRootCategory()): ?>

<div class="messages">
    <div class="message message-info info">
        The root category is not displayed on Magento's frontend and therefore it's not indexed within Algolia records.
        <br>To merchandise products, please select any sub-category.
    </div>
</div>

<?php return; endif; ?>

<?php

$configHelper = $block->getConfigHelper();

$indexName = $block->getCoreHelper()->getBaseIndexName();

$category = $block->getCategory();

$categoryId = $category->getId();
$categoryName = $category->getName();

$isConfig = [
    'appId' => $configHelper->getApplicationID(),
    'apiKey' => $configHelper->getSearchOnlyAPIKey(),
    'indexName' => $configHelper->getIndexPrefix() . 'default_products',
    'routing' => false,
    'searchParameters' => [
        'hitsPerPage' => $configHelper->getNumberOfProductResults(),
        'getRankingInfo' => true,
        'ruleContexts' => [
            '',
            'magento-category-'.$categoryId,
        ],
        'facetFilters' => [
            'categoryIds:'.$block->getCategory()->getId(),
        ],
    ],
];

?>

<div id="algolia_merchandising_search_box"></div>
<div id="algolia_merchandising_hits"></div>

<input type="hidden" name="algolia_merchandising_positions" value="" data-form-part="category_form" />

<script type="text/template" id="algolia_merchandising_all_items_template">
    <div>
        <p>
            On this page you see the exact products in the exact order
            as your customers see it on <b>"<?= $categoryName; ?>"</b> category page.
        </p>
        <p>
            Drag & drop products to a specific position and pin it there to have the product displayed always in this position.
        </p>
    </div>

    <label for="algolia_merchandising_autocomplete">
        Add a product to first position:
        <input type="text" id="algolia_merchandising_autocomplete" />
    </label>

    <div class="admin__data-grid-wrap admin__data-grid-wrap-static algolia_merchandising_items_table">
        <table class="data-grid">
            <thead>
                <tr>
                    <th class="data-grid-th">Image</th>
                    <th class="data-grid-th">ID</th>
                    <th class="data-grid-th">SKU</th>
                    <th class="data-grid-th">Name</th>
                    <th class="data-grid-th">Price</th>
                    <th class="data-grid-th">Pin it</th>
                </tr>
            </thead>
            <tbody>
                {{#hits}}
                    <tr data-objectid="{{ objectID }}" {{#_rankingInfo.promoted}}class="pinned"{{/_rankingInfo.promoted}}>
                        <td class="image_cell"><img src="{{ image_url }}" width="60" /></td>
                        <td>{{ objectID }}</td>
                        <td>{{{ _highlightResult.sku.value }}}</td>
                        <td>{{{ _highlightResult.name.value }}}</td>
                        <td>{{ price.USD.default_formated }}</td>
                        <td>
                            <span class="unpin_block">
                                Pinned <a href="#" class="unpinIt">UNPIN IT</a>
                            </span>
                            <span class="pin_block">
                                <a href="#" class="pinIt">PIN IT</a>
                            </span>
                        </td>
                    </tr>
                {{/hits}}
            </tbody>
        </table>
    </div>
</script>

<script type="text/template" id="algolia_merchandising_no_results">
    <div class="algolia_merchandising_no_results messages">
        <div class="message message-warning warning">
            Algolia didn't find any products in this category.
            If there are supposed to be some products, please reindex Products indexer.
        </div>
    </div>
</script>

<script type="text/template" id="algolia_merchandisign_table_row">
    <tr data-objectid="{{ objectID }}">
        <td class="image_cell"><img src="{{ image_url }}" width="60" /></td>
        <td>{{ objectID }}</td>
        <td>{{{ sku }}}</td>
        <td>{{{ name }}}</td>
        <td>{{ price.USD.default_formated }}</td>
        <td>
            <span class="unpin_block">
                Pinned <a href="#" class="unpinIt">UNPIN IT</a>
            </span>
            <span class="pin_block">
                <a href="#" class="pinIt">PIN IT</a>
            </span>
        </td>
    </tr>
</script>

<script type="text/template" id="algolia_merchandising_autocomplete_hit">
    <a class="algoliasearch-autocomplete-hit" href="{{ url }}">
        <div class="thumb"><img src="{{ image_url }}" /></div>

        <div class="info">
            {{{ _highlightResult.name.value }}}
        </div>

        <div class="price">
			<span class="right">
				{{ price.USD.default_formated }}
			</span>
        </div>
        <div class="algolia-clearfix"></div>
    </a>
</script>

<style>
    .algolia_merchandising_items_table em {
        font-style: normal;
        font-weight: bold;
    }

    .algolia_merchandising_items_table .image_cell {
        width: 90px;
    }

    .algolia_merchandising_items_table tr .unpin_block {
        display: none;
    }

    .algolia_merchandising_items_table tr .pin_block {
        display: inline;
    }

    .algolia_merchandising_items_table tr.pinned .unpin_block {
        display: inline;
    }

    .algolia_merchandising_items_table tr.pinned .pin_block {
        display: none;
    }

    /* AUTOCOMPLETE HIT */
    .aa-dropdown-menu {
        position: absolute;
        margin-top: 5px;
        right: 0;
        width: 100%;
        z-index: 10000 !important;
        border: 1px solid #adadad;
        border-radius: 5px;
        background: white;
    }

    @media (min-width: 992px) {
        .aa-dropdown-menu {
            width: 71.1%;
            min-width: 550px;
        }
    }

    .aa-dropdown-menu .aa-dataset-products .aa-suggestion {
        display: inline-block;
        width: 100%;
    }

    @media (min-width: 768px) {
        .aa-dropdown-menu .aa-dataset-products .aa-suggestion {
            display: inline-block;
        }
    }

    .aa-dataset-products .aa-suggestions:after {
        content:'';
        display:block;
        clear: both;
    }

    .aa-dataset-products .aa-suggestions {
        margin: 10px auto 10px auto;
    }

    .aa-dropdown-menu .algoliasearch-autocomplete-hit {
        display: block;
        position: relative;
        padding: 2px 10px;
        color: #303030;
        text-align: left;
        text-decoration: none;
    }

    .aa-dropdown-menu .aa-cursor .algoliasearch-autocomplete-hit {
        background-color: #f5d6c7;
    }

    .aa-dropdown-menu .algoliasearch-autocomplete-hit em {
        font-weight: bold;
        font-style: normal;
    }

    .aa-dropdown-menu .algoliasearch-autocomplete-hit .thumb {
        float: left;
        width: 55px;
    }

    .aa-dropdown-menu .algoliasearch-autocomplete-hit .thumb img {
        width: 55px;
    }

    .aa-dropdown-menu .algoliasearch-autocomplete-hit .info {
        margin-left: 15px;
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
        float: left;
        width: 380px;
        line-height: 59px;
    }

    .aa-dropdown-menu .algoliasearch-autocomplete-hit .price {
        float: right;
        font-weight: bold;
        line-height: 59px;
    }

    .algolia-clearfix {
        clear: both;
    }
</style>

<script>
    requirejs(['algoliaAdminBundle'], function (algoliaAdminBundle) {
        algoliaAdminBundle.$(function ($) {
        	var config = <?= json_encode($isConfig); ?>;

            var search = algoliaAdminBundle.instantsearch(<?= json_encode($isConfig); ?>);

            // // initialize SearchBox
            // search.addWidget(
             //    algoliaAdminBundle.instantsearch.widgets.searchBox({
             //        container: '#algolia_merchandising_search_box',
             //        placeholder: 'Search for products',
             //        reset: false,
             //        magnifier: false
             //    })
            // );

            // initialize hits widget
            search.addWidget(
                algoliaAdminBundle.instantsearch.widgets.hits({
                    container: '#algolia_merchandising_hits',
                    transformData: {
                        allItems: function(res) {
                            var positions = {};
                            for (var i = 0; i < res.hits.length; i++) {
                                var hit = res.hits[i],
                                    pinned = false,
                                    unpinnedDisplayMode = 'inline';

                                if (hit._rankingInfo.promoted === true) {
                                    positions[hit.objectID] = i;
                                    pinned = true;
                                }

                                res.hits[i]['pinned'] = true;
                            }

                            $('input[name="algolia_merchandising_positions"]').val(JSON.stringify(positions));

                            return res;
                        }
                    },
                    templates: {
                        allItems: $('#algolia_merchandising_all_items_template').html(),
                        empty: $('#algolia_merchandising_no_results').html()
                    },
                    escapeHits: true
                })
            );

            search.on('render', function() {
	            initAutocomplete();

                initSortableTable();
            });

            search.start();

            $(document).on('click', '.algolia_merchandising_items_table .pinIt', function(e) {
                $(this).closest('tr').addClass('pinned');

                regeneratePositionsValue();

                e.preventDefault();
                return false;
            });

            $(document).on('click', '.algolia_merchandising_items_table .unpinIt', function(e) {
	            $(this).closest('tr').removeClass('pinned');

	            regeneratePositionsValue();

                e.preventDefault();
                return false;
            });

            var initAutocomplete = function() {
	            var client = algoliaAdminBundle.algoliasearch(config.appId, config.apiKey),
                    index = client.initIndex(config.indexName),
                    template = algoliaAdminBundle.Hogan.compile($('#algolia_merchandising_autocomplete_hit').html()),
                    options = {
                        hitsPerPage: 8
                    },
                    sources = [{
                        source: algoliaAdminBundle.autocomplete.sources.hits(index, options),
                        name: 'products',
                        templates: {
                            suggestion: function (hit) {
                                return template.render(hit);
                            }
                        }
                    }];

	            $('#algolia_merchandising_autocomplete')
                    .autocomplete({ debug: true, hint: false }, sources)
		            .on('autocomplete:selected', function (e, suggestion, dataset) {
			            var newRowTemplateHtml = $('#algolia_merchandisign_table_row').html(),
                            newRowTemplate = algoliaAdminBundle.Hogan.compile(newRowTemplateHtml),
                            rowHtml = newRowTemplate.render(suggestion);

			            $('.algolia_merchandising_items_table tbody').prepend(rowHtml);
			            $('.algolia_merchandising_items_table tbody tr').last().remove();

			            regeneratePositionsValue();
		            });
            };

            var initSortableTable = function() {
	            $('.algolia_merchandising_items_table tbody').sortable({
		            containment: 'parent',
		            items: 'tr',
		            tolerance: 'pointer',
		            helper: sortableHelper,
		            start: function (event, ui) {
			            $(ui.item).css('margin-left', '10px');
		            },
		            stop: function () {
			            regeneratePositionsValue();
		            }
	            });

	            $('.algolia_merchandising_items_table tbody tr td').css('cursor', 'move');
            };

            var regeneratePositionsValue = function() {
	            var $positionsInput = $('input[name="algolia_merchandising_positions"]'),
		            positions = {};

	            $('.algolia_merchandising_items_table tbody tr').each(function(position) {
		            if ($(this).hasClass('pinned')) {
			            var objectId = $(this).data('objectid');
			            positions[objectId] = position;
		            }
	            });

	            $positionsInput.val(JSON.stringify(positions));
            };

            var sortableHelper = function(e, ui) {
                ui.children().each(function() {
                    $(this).width($(this).width());
                });

                return ui;
            };
        });
    });
</script>
